version: '3.4'
services:
  mirai:
    image: lss233/mirai-http:latest
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./mirai/bots:/docker/chatgpt-qq/mirai/bots
      - ./mirai/config:/docker/chatgpt-qq/mirai/config
      - ./mirai/data:/docker/chatgpt-qq/mirai/data
      - ./mirai/plugin-libraries:/docker/chatgpt-qq/mirai/plugin-libraries
      - ./mirai/libs:/docker/chatgpt-qq/mirai/libs
      # - ./mirai/config.json:/mirai/config.json # 如果你要修改 mcl 的设置，就解除这个注释
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:api-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      # GPT_ENGINE: text-davinci-003 # 如果你想使用付费模型，就解除注释
    ports:
      - 14500:14500
    volumes:
      - ./config.cfg:/docker/chatgpt-qq/config.cfg
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
      # - ./presets:/app/presets # 如果你想自定义预设，就解除注释
